### ISSUE TITLE
AttributeError: module 'scipy' has no attribute 'io' 이 문제는 왜 발생하나요?

### ISSUE THREAD

**Issue by Erickim7979** [chldkato/Tacotron-Korean-Tensorflow2#1]
안녕하세요.

타코트론에 관심이 많아서(개발자는 아니지만 ^^;;) 하나씩 따라하다 보니 마지막 python test2.py 을 실행하고 나면

Traceback (most recent call last):
  File "test2.py", line 42, in <module>
    test_step(mel, i)
  File "test2.py", line 31, in test_step
    scipy.io.wavfile.write(os.path.join(save_dir, '{}.wav'.format(idx)), sample_rate, wav)
AttributeError: module 'scipy' has no attribute 'io'

이러한 에러가 발생을 합니다.

텐스플로우는 최신버전이 설치되어 있습니다. (2.0 이상)

**Comment by chldkato** [comment]
아래의 방법 하나씩 해보세요
1. 맨위에 import scipy.io 추가한 후 실행
2. from scipy import io를 추가하고 31번째줄 scipy.io.wavfile 을 io.wavefile로 수정한 후 실행
3. import soundfile as sf를 추가한 후 31번째 줄을 아래의 코드로 수정한 후 실행
sf.write(os.path.join(save_dir, '{}.wav'.format(idx)), wav, sample_rate)

**Comment by Erickim7979** [comment]
> 아래의 방법 하나씩
> 
> 1. 맨위에 import scipy.io 추가 한 후 실행
> 2. from scipy import io를 추가하고 31 번째 줄 scipy.io.wavfile을 io.wavefile로 수정 한 후 실행
> 3. import soundfile as sf를 추가 한 후 31 번째 줄을 아래의 코드로 수정 한 후 실행 
>    sf.write (os.path.join (save_dir, '{} .wav'.format (idx)), wav, sample_rate)

1번 시도 실패
2번 시도 실패
3번 시도 성공!!!!

0.wav 파일이 생성되었습니다!!!!!

감사합니다!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
