### ISSUE TITLE
Training time

### ISSUE THREAD

**Issue by somasundaram97** [chldkato/Tacotron-Korean-Tensorflow2#3]
Hi. How long does the training module typically take? Is there a maximum defined step-count after which the training will converge? How to utilize my gpu to run this code? should I change any configuration parameters if I use my own dataset?

**Comment by chldkato** [comment]
There is no maximum step, so you should check each evaluation. This code is suitable for Korean, so you need to change utils/text.py and text part of preprocess.py for your language
